###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  myapp-postgres:
    image: postgres:15-alpine
    container_name: myapp-postgresql
    working_dir: /var/www/myapp
    ports:
      - 5432:5432
    volumes:
      - ../cakephp:/var/www/myapp
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DATABASE}

  # myapp-mysql:
  #   image: 'mysql:8.0'
  #   container_name: myapp-mysql
  #   working_dir: /var/www/myapp
  #   volumes:
  #       - ../mysql:/var/lib/mysql
  #       - ../mysql-files:/var/lib/mysql-files
  #       - ../cakephp:/var/www/myapp
  #       - ./mysql/my.cnf:/etc/mysql/my.cnf
  #   ports:
  #     - "8106:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${DATABASE}
  #     - MYSQL_USER=${USER}
  #     - MYSQL_PASSWORD=${PASSWORD}

  myapp-nginx:
    image: 'nginx:alpine'
    container_name: myapp-nginx
    working_dir: /var/www/myapp
    volumes:
        - ../cakephp:/var/www/myapp
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8180:80"
    links:
     - myapp-php-fpm

  myapp-php-fpm:
    build: ./php-fpm
    container_name: myapp-php-fpm
    working_dir: /var/www/myapp
    volumes:
      - ../cakephp:/var/www/myapp
      - ./php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini

    links:
      #- myapp-mysql
      - myapp-postgres
